development:
  adapter: postgresql
  encoding: unicode
  database: online_learning
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: online_learning_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DB_URL"] %>
